server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / { try_files $uri $uri/ $uri.html /index.html; }

    location /api/ {
        proxy_pass         http://API_INTERNAL/api/;
        proxy_set_header   Host                  $host;
        proxy_set_header   X-Forwarded-For       $proxy_add_x_forwarded_for;
        proxy_set_header   x-ms-client-principal $http_x_ms_client_principal;
    }

    location = /.auth/me {
        default_type application/json;
        return 200 '{"clientPrincipal":{"userId":"local","userDetails":"admin@local","identityProvider":"aad","userRoles":["authenticated","admin"]}}';
    }
    location ^~ /.auth/login/ { return 302 /; }
    location ^~ /.auth/logout { return 302 /; }
}